### ISSUE TITLE
Component CSS is not applied in NativeScript 7

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/nativescript-vue#715]
If you recently upgraded your application to NativeScript 7.0 you likely ran into an issue where component css from `<style>` blocks doesn't get applied. 

The issue has been identified, and fixed in `@nativescript/webpack@3.0.3`.

## Verifying the fix

Run the following commands to install the fixed version of `@nativescript/webpack`
```
ns clean

npm i --save-dev @nativescript/webpack@3.0.3

ns run <platform>
```

If the issue is solved for your project, please add a 👍 on this issue. In case you are still having an issue, please leave a comment with details: 
 - output from `tns doctor`

### NativeScript-Vue 2.8.1 also released

With a minor refactor, there are no new features for `2.8.1` but you are encouraged to update.

Make sure to update both `nativescript-vue` and `nativescript-vue-template-compiler` to `2.8.1`.

**Comment by lochstar** [comment]
When running `"./node_modules/.bin/update-ns-webpack --configs"` I get an error `Error: Cannot find module '../projectHelpers'`

**Comment by rigor789** [comment]
@lochstar delete your webpack config, and re-install your dependencies. It should automatically create the latest config.

**Comment by mict-exp** [comment]
This solves my problem. Thank you.

**Comment by romandragan** [comment]
Works with `@nativescript/webpack@3.0.1-rc.0` 👍

Doesn't work with `@nativescript/webpack@3.0.2` 🤔

**Comment by rigor789** [comment]
Finally released in `@nativescript/webpack@3.0.3`

**Comment by mict-exp** [comment]
Hello Igor.

Thank you for your message. 
However, I have been facing rather with a hard nut to crack. This was actually working perfectly in NS 6.5 before I upgraded to NS 7. Since I upgraded to NS 7, I have been battling with this error of “Cannot read property sdkVersion of undefined”. I called this using platform.device.sdkVersion in my script. Everywhere it sees this, it throws that error. 
Another error I have been battling with is the error that came up while building for IOS. It throws Nativesript/Nativescript.h file not found. With this error, I can’t proceed to doing anything.

Please help.

**Comment by aafix2** [comment]
Hello, I still having an issue after update on ns7

`Can't find variable: ___CSS_LOADER_EXPORT___`

**tns doctor**

✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.6.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.8 version and is up to date.
✔ Component @nativescript/core has 7.0.3 version and is up to date.
✔ Component tns-ios has 6.5.2 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.

**dependencies**

"dependencies": {
    "@nativescript/core": "^7.0.0",
    "@nativescript/theme": "^2.5.0",
    "@nativescript/webpack": "3.0.3",
    "nativescript-vue": "2.8.1",
    "vuex": "^3.1.3",
    "vuex-module-decorators": "^0.17.0"
  },
  "devDependencies": {
    "@nativescript/types": "^7.0.0",
    "nativescript-vue-template-compiler": "2.8.1",
    "node-sass": "^4.14.1",
    "tns-android": "6.5.3",
    "tns-ios": "6.5.2",
    "typescript": "^3.2.4",
    "vue": "^2.6.12",
    "vue-class-component": "^7.1.0",
    "vue-eslint-parser": "^7.0.0",
    "vue-loader": "^15.2.6",
    "vue-property-decorator": "^9.0.0",
    "vue-template-compiler": "^2.0.0",
},

**Detail**

`JavaScript error:
file: app/modules/fonticon/component/Icon.vue?98e1:12:0: JS ERROR ReferenceError: Can't find variable: ___CSS_LOADER_EXPORT___
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: ___CSS_LOADER_EXPORT___
at
file: app/modules/fonticon/component/Icon.vue?98e1:12:0
at ../node_modules/@nativescript/webpack/helpers/style-hot-loader.js!../node_modules/@nativescript/webpack/helpers/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js?!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/sass-loader/dist/cjs.js!../node_modules/vue-loader/lib/index.js?!./modules/fonticon/component/Icon.vue?vue&type=style&index=0&id=32775528&lang=scss&scoped=true&(file:///app/bundle.js:986:34)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at ./modules/fonticon/component/Icon.vue?vue&type=style&index=0&id=32775528&lang=scss&scoped=true&(file: app/modules/fonticon/component/Icon.vue?f356:1:0)
at __webpack_require__(file: app/webpack/bootstrap:816:0)
at fn(file: app/webpack/bootstrap:120:0)
at ./modules/fonticon/component/Icon.vue(file: app/modules/fonticon/component/Icon.vue:1:0)
at __<…>`
